export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const NEW_MESSAGE = 'NEW_MESSAGE';
export const LAST_MESSAGES = 'LAST_MESSAGES';
export const LOGGED_IN_USERS = 'LOGGED_IN_USERS';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';




